openapi: 3.0.0
info:
  title: maney
  version: v0.0.1
tags:
  - name: User
  - name: Account
  - name: Category
  - name: Shop
  - name: Fee
  - name: Daily Item
  - name: Repeating Item
paths:
  /log-in:
    post:
      summary: user logs in
      tags: ["User"]
      operationId: LogIn
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
              required:
                - id
                - password
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
  /log-out:
    post:
      summary: user logs out
      tags: ["User"]
      operationId: LogOut
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
  /sign-up:
    post:
      summary: user signs up
      tags: ["User"]
      operationId: SignUp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
                name:
                  type: string
              required:
                - id
                - password
                - name
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
  /users/config:
    put:
      summary: update user config
      tags: ["User"]
      operationId: UpdateUserConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserConfig"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    get:
      tags: ["User"]
      operationId: GetUserConfig
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserConfig"
  /users/accounts:
    post:
      summary: create an account for user
      tags: ["Account"]
      operationId: CreateAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ObjectOID"
        default:
          $ref: "#/components/responses/DefaultResponse"
    get:
      summary: list all user's accounts
      tags: ["Account"]
      operationId: ListUserAccounts
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: "#/components/schemas/ObjectOID"
                    - $ref: "#/components/schemas/Account"
                    - type: object
                      properties:
                        balance:
                          $ref: "#/components/schemas/Decimal"
  /users/accounts/{account-oid}:
    parameters:
      - name: account-oid
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OID"
    put:
      summary: update account
      tags: ["Account"]
      operationId: UpdateAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    delete:
      summary: delete account
      tags: ["Account"]
      operationId: DeleteAccount
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
  /users/categories:
    post:
      summary: create category
      tags: ["Category"]
      operationId: CreateCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    get:
      summary: list all user's categories
      tags: ["Category"]
      operationId: ListUserCategories
      parameters:
        - name: type
          in: query
          schema:
            $ref: "#/components/schemas/CategoryType"
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
  /users/categories/{category-oid}:
    parameters:
      - name: category-oid
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OID"
    put:
      summary: update category
      tags: ["Category"]
      operationId: UpdateCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    delete:
      summary: delete category
      tags: ["Category"]
      operationId: DeleteCategory
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
  /users/shops:
    post:
      tags: ["Shop"]
      operationId: CreateShop
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Shop"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    get:
      summary: list all user's shops
      tags: ["Shop"]
      operationId: ListUserShops
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Shop"
  /users/shops/{shop-oid}:
    parameters:
      - name: shop-oid
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OID"
    put:
      tags: ["Shop"]
      operationId: UpdateShop
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Shop"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    delete:
      tags: ["Shop"]
      operationId: DeleteShop
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
  /users/fees:
    post:
      tags: ["Fee"]
      operationId: CreateFee
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fee"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    get:
      summary: list all user's fees
      tags: ["Fee"]
      operationId: ListUserFees
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Fee"
  /users/fees/{fee-oid}:
    parameters:
      - name: fee-oid
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OID"
    put:
      tags: ["Fee"]
      operationId: UpdateFee
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fee"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    delete:
      tags: ["Fee"]
      operationId: DeleteFee
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
  /users/daily-items:
    post:
      tags: ["Daily Item"]
      operationId: CreateDailyItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DailyItem"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    get:
      tags: ["Daily Item"]
      operationId: ListUserDailyItems
      parameters:
        - name: date
          in: query
          description: today is in default
          schema:
            type: string
            format: date
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DailyItem"
  /users/daily-items/{daily-item-oid}:
    parameters:
      - name: daily-item-oid
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OID"
    put:
      tags: ["Daily Item"]
      operationId: UpdateDailyItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DailyItem"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    delete:
      tags: ["Daily Item"]
      operationId: DeleteDailyItem
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
  /users/daily-items/export:
    get:
      tags: ["Daily Item"]
      operationId: ExportDailyItems
      parameters:
        - name: format
          in: query
          schema:
            type: string
            enum:
              - json
              - xml
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DailyItem"
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DailyItem"
                xml:
                  name: items
                  wrapped: true
  /users/daily-items/import:
    post:
      tags: ["Daily Item"]
      operationId: ImportDailyItems
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/DailyItem"
          application/xml:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/DailyItem"
              xml:
                name: items
                wrapped: true
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
  /users/repeating-items:
    post:
      tags: ["Repeating Item"]
      operationId: CreateRepeatingItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RepeatingItem"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    get:
      summary: list all user's repeating items
      tags: ["Repeating Item"]
      operationId: ListUserRepeatingItems
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RepeatingItem"
  /users/repeating-items/{repeating-item-oid}:
    parameters:
      - name: repeating-item-oid
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/OID"
    put:
      tags: ["Repeating Item"]
      operationId: UpdateRepeatingItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RepeatingItem"
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
    delete:
      tags: ["Repeating Item"]
      operationId: DeleteRepeatingItem
      responses:
        default:
          $ref: "#/components/responses/DefaultResponse"
components:
  schemas:
    Decimal:
      type: string
      format: float64
      example: 0.0
      description: a string represented as a float64
    UserConfig:
      type: object
      properties:
        compare_items_in_different_shop:
          type: boolean
        compare_items_in_same_shop:
          type: boolean
    OID:
      type: string
      format: uint64
      example: 0
    ObjectOID:
      type: object
      properties:
        oid:
          $ref: "#/components/schemas/OID"
    Account:
      type: object
      properties:
        name:
          type: string
          description: account name
        icon_oid:
          $ref: "#/components/schemas/OID"
        initial_balance:
          $ref: "#/components/schemas/Decimal"
      required:
        - name
    CategoryType:
      type: string
      enum: ["expense", "income"]
    Category:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/CategoryType"
        name:
          type: string
        icon_oid:
          $ref: "#/components/schemas/OID"
          description: icon oid
      required:
        - type
        - name
    Shop:
      type: object
      properties:
        name:
          type: string
        address:
          type: string
      required:
        - name
    Fee:
      type: object
      properties:
        name:
          type: string
        value:
          type: object
          description: choose one of properties
          properties:
            rate:
              $ref: "#/components/schemas/Decimal"
            fixed:
              $ref: "#/components/schemas/Decimal"
    Item:
      type: object
      properties:
        name:
          type: string
        category:
          type: array
          items:
            $ref: "#/components/schemas/OID"
            xml:
              name: category
          minLength: 1
          xml:
            name: categories
            attribute: false
            wrapped: true
        shop_oid:
          $ref: "#/components/schemas/OID"
        quantity:
          type: object
          properties:
            value:
              $ref: "#/components/schemas/Decimal"
        fee:
          type: integer
        price:
          $ref: "#/components/schemas/Decimal"
        memo:
          type: string
      required:
        - name
        - price
    DailyItem:
      allOf:
        - type: object
          properties:
            date:
              type: string
              format: date
          required:
            - date
        - $ref: "#/components/schemas/Item"
      xml:
        name: item
    RepeatingItem:
      type: object
      properties:
        item:
          $ref: "#/components/schemas/Item"
        valid:
          type: object
          properties:
            start:
              type: string
              format: date
            end:
              type: string
              format: date
        frequency:
          type: object
          properties:
            durations:
              type: array
              items:
                type: object
                properties:
                  value:
                    type: integer
                  unit:
                    type: string
                    enum:
                      - ONE_DAY
                      - ONE_MONTH
                      - ONE_YEAR
                      - EVERY_WORK_DAY
                required:
                  - value
                  - unit
      required:
        - item
        - frequency
  responses:
    DefaultResponse:
      description: ""
